name: Take screenshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Function
        run: cd screenshot && node index.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: 'Update Content'
          repository: .
          commit_user_name: NewDev0Bot
          commit_user_email: Newdev0Bot@outlook.com
          commit_author: Auto <Newdev0Bot@outlook.com>
      
     
